testname: Reverb Study v1
testId: reverb_study_v1
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php


pages:

    - type: generic
      id: first_page
      name: Welcome
      content: Welcome to the reverb study listening test (v1)! 
      
    - 
          - random

          - type: mushra
            id: speech_rec01
            name: MUSHRA - Speech - Receiver 1
            content: The following signals had their reverberation rendered in different ways. Please rate them according to their similarity to the reference.
            enableLooping: true 
            reference: configs/resources/audio/Reference_8bands_rec01_Speech_000.wav
            createAnchor35: false
            createAnchor70: false
            stimuli:
                C1: configs/resources/audio/LivingRoom_8bands_rec01_Speech_000.wav
                C2: configs/resources/audio/LivingRoom_3_8bands_rec01_Speech_000.wav
                C3: configs/resources/audio/LivingRoom_6_8bands_rec01_Speech_000.wav
                C4: configs/resources/audio/Anchor_8bands_rec01_Speech_000.wav

          - type: mushra
            id: speech_rec02
            name: MUSHRA - Speech - Receiver 2
            content: The following signals had their reverberation rendered in different ways. Please rate them according to their similarity to the reference.
            enableLooping: true 
            reference: configs/resources/audio/Reference_8bands_rec02_Speech_000.wav
            createAnchor35: false
            createAnchor70: false
            stimuli:
                C1: configs/resources/audio/LivingRoom_8bands_rec02_Speech_000.wav
                C2: configs/resources/audio/LivingRoom_3_8bands_rec02_Speech_000.wav
                C3: configs/resources/audio/LivingRoom_6_8bands_rec02_Speech_000.wav
                C4: configs/resources/audio/Anchor_8bands_rec02_Speech_000.wav

          - type: mushra
            id: speech_rec03
            name: MUSHRA - Speech - Receiver 3
            content: The following signals had their reverberation rendered in different ways. Please rate them according to their similarity to the reference.
            enableLooping: true 
            reference: configs/resources/audio/Reference_8bands_rec03_Speech_000.wav
            createAnchor35: false
            createAnchor70: false
            stimuli:
                C1: configs/resources/audio/LivingRoom_8bands_rec03_Speech_000.wav
                C2: configs/resources/audio/LivingRoom_3_8bands_rec03_Speech_000.wav
                C3: configs/resources/audio/LivingRoom_6_8bands_rec03_Speech_000.wav
                C4: configs/resources/audio/Anchor_8bands_rec03_Speech_000.wav

          - type: mushra
            id: takeFive_rec01
            name: MUSHRA - Take Five - Receiver 1
            content: The following signals had their reverberation rendered in different ways. Please rate them according to their similarity to the reference.
            enableLooping: true 
            reference: configs/resources/audio/Reference_8bands_rec01_TakeFive_000.wav
            createAnchor35: false
            createAnchor70: false
            stimuli:
                C1: configs/resources/audio/LivingRoom_8bands_rec01_TakeFive_000.wav
                C2: configs/resources/audio/LivingRoom_3_8bands_rec01_TakeFive_000.wav
                C3: configs/resources/audio/LivingRoom_6_8bands_rec01_TakeFive_000.wav
                C4: configs/resources/audio/Anchor_8bands_rec01_TakeFive_000.wav

          - type: mushra
            id: takeFive_rec02
            name: MUSHRA - Take Five - Receiver 2
            content: The following signals had their reverberation rendered in different ways. Please rate them according to their similarity to the reference.
            enableLooping: true 
            reference: configs/resources/audio/Reference_8bands_rec02_TakeFive_000.wav
            createAnchor35: false
            createAnchor70: false
            stimuli:
                C1: configs/resources/audio/LivingRoom_8bands_rec02_TakeFive_000.wav
                C2: configs/resources/audio/LivingRoom_3_8bands_rec02_TakeFive_000.wav
                C3: configs/resources/audio/LivingRoom_6_8bands_rec02_TakeFive_000.wav
                C4: configs/resources/audio/Anchor_8bands_rec02_TakeFive_000.wav

          - type: mushra
            id: takeFive_rec03
            name: MUSHRA - Take Five - Receiver 3
            content: The following signals had their reverberation rendered in different ways. Please rate them according to their similarity to the reference.
            enableLooping: true 
            reference: configs/resources/audio/Reference_8bands_rec03_TakeFive_000.wav
            createAnchor35: false
            createAnchor70: false
            stimuli:
                C1: configs/resources/audio/LivingRoom_8bands_rec03_TakeFive_000.wav
                C2: configs/resources/audio/LivingRoom_3_8bands_rec03_TakeFive_000.wav
                C3: configs/resources/audio/LivingRoom_6_8bands_rec03_TakeFive_000.wav
                C4: configs/resources/audio/Anchor_8bands_rec03_TakeFive_000.wav

    - type: finish
      name: Thank you
      content: Thank you for attending!
      showResults: true
      writeResults: true
      questionnaire:
          - type: text
            label: eMail
            name: email
          - type: number
            label: Age
            name: age
            min: 0
            max: 100
            default: 30
          - type: likert
            name: gender
            label: Gender
            response:
             - value: female
               label: Female
             - value: male
               label: Male
             - value: other
               label: Other
